package doshilos;

public class DosHilos extends javax.swing.JFrame {

    private static final int TOPE_SUPERIOR = 20, TOPE_INFERIOR = 0;
    
    private int cuentaAdelante = TOPE_INFERIOR, cuentaAtras = TOPE_SUPERIOR;
    
    //runnable, thread
    
    /**
     * Creates new form DosHilos
     */
    public DosHilos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taAdelante = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAtras = new javax.swing.JTextArea();
        btDo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(524, 347));

        taAdelante.setColumns(20);
        taAdelante.setRows(5);
        jScrollPane1.setViewportView(taAdelante);

        taAtras.setColumns(20);
        taAtras.setRows(5);
        jScrollPane2.setViewportView(taAtras);

        btDo.setText("do!");
        btDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btDo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btDo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private class HebraContadora extends Thread {
        @Override
        public void run() {
            cuentaHaciaAdelante();
        }
    }
    
    private void cuentaHaciaAdelante() {
        System.out.println("hebra 2:" + Thread.currentThread().getName());
        taAdelante.setText("");
        for (cuentaAdelante = TOPE_INFERIOR; cuentaAdelante < TOPE_SUPERIOR; cuentaAdelante++) {
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
            }
            taAdelante.append(cuentaAdelante + "\n");
        }
    }
    
    private void cuentaHaciaAtrás() {
        System.out.println("hebra 3:" + Thread.currentThread().getName());
        taAtras.setText("");
        for (cuentaAtras = TOPE_SUPERIOR; cuentaAtras > TOPE_INFERIOR; cuentaAtras--) {
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
            }
            taAtras.append(cuentaAtras + "\n");
        }
    }
    
    private void btDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoActionPerformed
        //cuentaHaciaAdelante();
        //cuentaHaciaAtrás();
        /*Thread hebra = new Thread() {
            @Override
            public void run() {
                cuentaHaciaAdelante();
            } 
        };*/
        Thread hebra2 = new Thread() {
            @Override
            public void run() {
                cuentaHaciaAtrás();
            } 
        };
        //hebra.start();
        HebraContadora h = new HebraContadora();
        h.start();
        hebra2.start();
    }//GEN-LAST:event_btDoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        System.out.println("main:" + Thread.currentThread().getName());
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DosHilos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DosHilos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DosHilos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DosHilos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                System.out.println("hebra 1:" + Thread.currentThread().getName());
                new DosHilos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taAdelante;
    private javax.swing.JTextArea taAtras;
    // End of variables declaration//GEN-END:variables
}
